### PR TITLE
refactor: adapt to new network data APIs

### LINKED ISSUE #268: [doc] we need to explain those unlinked nodes in networks
## Description
image

I remember there is something like "threshold" or so in the code that related to networks, so the unlinked nodes are designed to be unlinked, but our users do not know.

We should figure it out and explain it to our users.

## Type of Issue
- [ ] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [x] Documention incomplete
- [ ] Test Improvement
- [ ] Raise a Question

### LINKED ISSUE #552: [Refactor] refactor 4 networks with latest data APIs
### Description

See https://github.com/X-lab2017/open-digger/issues/1081#issuecomment-1359331214

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [x] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [x] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- resolve #552
- resolve #268

## Details

- [x] API adaptation
- [x] filter out edges with samll weight to make graph charts sparse and clear
- [x] make the networks look better
- [x] add docs to explain the edge triming strategy
- [x] update screenshots in READMEs

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi @frank-zsy, I'm working with edges filtering(triming) and my idea is to choose a fixed value(1~3 maybe) as the threshold so edges with smaller value will be simply dropped.

At the moment I find edge values in a `repo's developer network` are also `global`. For example, `frank-zsy -> tyn1998` is always 15.8 no matter the edge is in `hypertrons-crx's developer network`, `open-digger's developer network` or `developer's developer network`. While currently node values in a `repo's developer network` is `local` to that specific repo.

Back to the edges filtering topic. There is chance that an actually unwanted edge is reserved just because its `global` value is greater than the threshold, however the fact is, its `local` value is very small which means the two developers have little connection in that repo. But the edge is not removed in this scenario.

In contrast to the current network data, I find edge values in old `repo's developer network` data differ from repo to repo:

image

image

What do you think of the issue? Can it be an issue?

**Comment by tyn1998** [comment]
The Graph was trimmed(fine tuned) for better look.

e.g. Hypercrx:

image

e.g. OpenDigger:

image

**Comment by tyn1998** [comment]
docs to explain edge triming strategy:

image

image

**Comment by frank-zsy** [comment]
> At the moment I find edge values in a `repo's developer network` are also `global`. For example, `frank-zsy -> tyn1998` is always 15.8 no matter the edge is in `hypertrons-crx's developer network`, `open-digger's developer network` or `developer's developer network`. While currently node values in a `repo's developer network` is `local` to that specific repo.
> What do you think of the issue? Can it be an issue?

Yes, in current implementation, relationships between developers' are always global relationships rather than in project relationship. In project relationship requires issue level collaboration but not repo level which is more difficult than repo level right now since issue is not represented in Neo4j database.

**Comment by frank-zsy** [comment]
@tyn1998 Networks without some low weight edges surely looks better.

**Comment by tyn1998** [comment]
> Yes, in current implementation, relationships between developers' are always global relationships rather than in project relationship. In project relationship requires issue level collaboration but not repo level which is more difficult than repo level right now since issue is not represented in Neo4j database.

OK, so we will use these data.

> Networks without some low weight edges surely looks better.

Well, networks for big repos such as vscode are still dense because edge values of those networks are generally higher than the thresholds(for repo-repo is 5, for developer-developer is 2.5) so hardly an edge is cut:

image

I considered "percent" rather a fixed threshold first but for me the "percent" strategy makes less sense so I chose the latter one.

---

If you think the strategy applied is satisfying, this PR will be reviewed by someone and then merged.

**Comment by frank-zsy** [comment]
I think the density for vscode network is quite desirable too, good to me~

**Comment by tyn1998** [comment]
@wj23027 @andyhuang18 Hi guys, would you mind pulling this branch to your machines and have a test?

@wxharry could you please review this PR and approve it?

And happy new year!

**Comment by andyhuang18** [comment]
Hi~happy new year. I fetched this branch and test it right now
screenshot
screenshot2

**Comment by wj23027** [comment]
This is the result of testing on my machine~
项目关系网络图
开发者协作网络图

**Comment by wxharry** [comment]
Hi, Thank your contribution. Here is some questions I had during the test.
1. seperate cluster. As we simply remove edges below the threshold, there could be a completely seperate cluster without the current repo in the Project Correlation Network. It could be confusing sometimes. We might need to at least explain that to the users.
image
2. useless mocking code. Looks like all the code that use mocking are removed, do we still need the code within `src/mock/`?

**Comment by tyn1998** [comment]
Hi @wxharry, thanks for reviewing the code.

1. I do worry those possible separate clusters might confuse users. I have added explanation on removed edges and assumed that users can understand why some edges disappear. But it is still counterintuitive, rihgt? Maybe I can modify the code to **always reserve edges that containing the current repo/user**, what do you think?
2. As you pointed out, we do not need them anymore. In fact, I removed these code in https://github.com/hypertrons/hypertrons-crx/pull/547/commits/4c3d2677f8da86dfe0a56bbe3d1be86f3868fc35 to get a minimal Hypercrx. But that is for a further iteration plan so I think we should remove them in this PR, too.

**Comment by wxharry** [comment]
> 1. I do worry those possible separate clusters might confuse users. I have added explanation on removed edges and assumed that users can understand why some edges disappear. But it is still counterintuitive, rihgt? Maybe I can modify the code to **always reserve edges that containing the current repo/user**, what do you think?

I don't have any idea, either. IMO, it is fine to have some separate nodes or small clusters. But the cluster I mentioned before is way too large and it doesn't include the target repo.

> 2. As you pointed out, we do not need them anymore. In fact, I removed these code in [4c3d267](https://github.com/hypertrons/hypertrons-crx/commit/4c3d2677f8da86dfe0a56bbe3d1be86f3868fc35) to get a minimal Hypercrx. But that is for a further iteration plan so I think we should remove them in this PR, too.

Got it. Looking forwards to the new hypercrx. 😆

**Comment by tyn1998** [comment]
> Maybe I can modify the code to always reserve edges that containing the current repo/user, what do you think?

I will try it out and attach some screenshots here, then we make a decision.

**Comment by tyn1998** [comment]
Well, it's difficult to make a decision cause both have pros and cons. But still, I like the sparse version(the one in left side below) a bit more. How about you guys? @wxharry @frank-zsy @zhicheng-ning @xgdyp @will-ww

Contrast:

image

image

image

image

image

image

**Comment by zhicheng-ning** [comment]
> I like the sparse version(the one on left side below) a bit more. How about you guys?

As for me, disconnected graph makes me confusion when I first saw it. Users may lose information between different subgragh. One of my suggestions is to show the full connection information by default and provide a custom option to show sparse version if the technical implementation is not too difficult.

**Comment by wxharry** [comment]
I prefer the sparse version as well. I suggest we keep the sparse version in this pr since this pr is about new data APIs and may open an issue for further discussion on how to deal with the graph display.

**Comment by tyn1998** [comment]
>  I suggest we keep the sparse version in this pr since this pr is about new data APIs and may open an issue for further discussion on how to deal with the graph display.

Good idea, in fact the networks before refactoring had some edges removed (they had been removed before data files were generated). While the threshold seemed smaller than the ones we adopt here.

> As for me, disconnected graph makes me confusion when I first saw it. Users may lose information between different subgragh. One of my suggestions is to show the full connection information by default and provide a custom option to show sparse version if the technical implementation is not too difficult.

This is a great idea and I'll consider it when we improve the networks next time. Thank you @zhicheng-ning!

Hi @wxharry, you may review the PR and approve it :-)

**Review by wxharry — APPROVED** [review]

**Pull request merged**
