### PR TITLE
fix: resolve aligment issues (#649)

### LINKED ISSUE #649: [improvement] CSS styles update needed to ensure aligned
### Description

Some styles of the charts are not correctly aligned with its title and the content. As illustrated in the screenshot of the `Developer Collaboration Network`, the styles may not be well set. We don't have a detailed UI design for that, so as long as it is compatible with Github, it will fine.

image

### PR DESCRIPTION
**Pull request by stealth-bombeer**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- fix #649 

## Details

 Currently the Developer Network/Most Participated Repo  of user profile is not aligned leading to misalignments of the description and the graph I've added appropriate styles to the following components such that they align according to their parent component 

Split

fullscreen

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others

N.A

### CODE REVIEW

**Comment by wxharry** [comment]
@stealth-bombeer Thank you for the contribution! Could you please add some screenshots to show the UI changes? It would be very helpful for others to check out. Thanks!

**Comment by stealth-bombeer** [comment]
@wxharry , i've added pictures when screen is resized as well in fullscreen mode same changes are being applied to Most Participated Repo

**Comment by stealth-bombeer** [comment]
> > @wxharry , i've added pictures when screen is resized as well in fullscreen mode same changes are being applied to Most Participated Repo
> 
> Thanks, nice work! Could you also align the graph title and the period? I believe they are supposed to be in the same row. 😆

They are aligned in a block manner because when the screen becomes smaller the period tends to float which  lead to issue(#647 ) collapsing of graph and description ,even the Perceptor Tab of Repo is designed the same way 🙂

**Comment by wxharry** [comment]
> They are aligned in a block manner because when the screen becomes smaller the period tends to float on the graph container which lead to issue(#647 ) collapsing of graph and description ,even the Perceptor Tab of Repo is designed the same way 🙂

The fix to the repo graphs is fine, the title and period is not separate. But this fix splits title and period into two lines which is not expected.

Also, the developer graphs also have the issue similar to #647. I wonder if you would like to fix that?

**Comment by stealth-bombeer** [comment]
> > They are aligned in a block manner because when the screen becomes smaller the period tends to float on the graph container which lead to issue(#647 ) collapsing of graph and description ,even the Perceptor Tab of Repo is designed the same way 🙂
> 
> The fix to the repo graphs is fine, the title and period is not separate. But this fix splits title and period into two lines which is not expected.
> 
> Also, the developer graphs also have the issue similar to #647. I wonder if you would like to fix that?

Alright got it,i'll try to make it responsive i.e i'll wrap the period to the next line only when it is colliding with the title & will be attaching a video clip

**Comment by stealth-bombeer** [comment]
> > They are aligned in a block manner because when the screen becomes smaller the period tends to float on the graph container which lead to issue(#647 ) collapsing of graph and description ,even the Perceptor Tab of Repo is designed the same way 🙂
> 
> The fix to the repo graphs is fine, the title and period is not separate. But this fix splits title and period into two lines which is not expected.
> 
> Also, the developer graphs also have the issue similar to #647. I wonder if you would like to fix that?

I've committed all the changes as asked by you ,now you can take a look when you're free

**Review by tyn1998 — APPROVED** [review]
Tested and LGTM, thank you so much @stealth-bombeer !

image

**Comment by tyn1998** [comment]
/approve

Hi @stealth-bombeer, we are currently developing [v1.9.0](https://github.com/hypertrons/hypertrons-crx/tree/v1.9.0), where we introduced [a brand new feature loading mechanism](https://github.com/hypertrons/hypertrons-crx/pull/548). In this repo, most time we follow [the GitHub flow](https://scottchacon.com/2011/08/31/github-flow.html), i.e. we only maintain a single `master` branch. However, considering that v1.9.0 is a huge task we cannot finish it in short time, we created another branch(v1.9.0) to work on with.

That is a trouble, we should often pick changes in `master` and apply them to `v1.9.0` again. The solution is we should finish v1.9.0 ASAP 😆. So would you mind applying all changes you made to `master` so far to `v1.9.0` and create a PR to that branch?

**Comment by stealth-bombeer** [comment]
> /approve
> 
> Hi @stealth-bombeer, we are currently developing [v1.9.0](https://github.com/hypertrons/hypertrons-crx/tree/v1.9.0), where we introduced [a brand new feature loading mechanism](https://github.com/hypertrons/hypertrons-crx/pull/548). In this repo, most time we follow [the GitHub flow](https://scottchacon.com/2011/08/31/github-flow.html), i.e. we only maintain a single `master` branch. However, considering that v1.9.0 is a huge task we cannot finish it in short time, we created another branch(v1.9.0) to work on with.
> 
> That is a trouble, we have to often pick changes in `master` and apply them to `v1.9.0` again. The solution is to finish v1.9.0 ASAP 😆. So would you mind applying all changes you made to `master` so far to `v1.9.0` and create a PR to that branch?

Sure,i'll make all the necessary changes and create a PR for v1.9.0 branch 👍

**Comment by tyn1998** [comment]
[git worktree](https://git-scm.com/docs/git-worktree) is recommended for working on multiple branches(with different dependencies) in the same time :)

**Pull request merged**
