### PR TITLE
feat: chat widget for DocsGPT

### LINKED ISSUE #599: [Feature] I would like a new chat bot feature for Hypercrx
### Description

Hi, Hypercrx community. As ChatGPT is on fire right now, I think we can add a new feature in Hypercrx which is a chat bot for an open source project.

A popup chat box can be embedded into the pages which has a model for their documents.

I can provide chat service for the chatting.

Here is an example of the chat box:

image

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [x] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- resolve #599

## Details

Working on this feature...A demo looks like this:

image

Todo:

- [x] check whether current repo is supported by the DocsGPT service (check [this file](https://oss.x-lab.info/hypercrx/docsgpt_active_docs.json))
- [x] prompt users with how to contact us for new docs support
- [x] handle repo switches
- [x] themes for light and dark
- [x] lock input and trigger animation when "thinking"
- [x] add history to requests
- [x] message bubbles are too narrow
- [x] allow disable/enable
- [x]  issue link for requesting new docs

Next time:

- [ ] README
- [ ] enable emoji
- [ ] i18n
- [ ] bug: the widget remains where it should not exist
- [ ] should also run in Org page?

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by tyn1998** [comment]
https://user-images.githubusercontent.com/32434520/224928346-ef7d25a3-f257-48e7-9058-cbb3356051c7.mp4

Basicly it works :)

**Comment by tyn1998** [comment]
| Dark | Light |
| --- | --- |
| image | image|

**Comment by tyn1998** [comment]
image

**Comment by tyn1998** [comment]
Hi @lhbvvvvv @wj23027 @andyhuang18 @frank-zsy @wxharry, could you please fetch this PR and have a test?

**Comment by wj23027** [comment]
I have test it , everything works well~

And I have a question. Is this emoji unclickable?

**Comment by andyhuang18** [comment]
It seems good~

image

**Comment by tyn1998** [comment]
@andyhuang18 @wj23027 thank you for the tests!

> And I have a question. Is this emoji unclickable?

Yes, I disabled emoji because I lost patience yesterday to fine tune the styles for the two themes (disabling emoji panel could save a lot of time). Maybe I should enable it and tune its style today 😆 

hi @lhbvvvvv, you could test the feature with dark theme being set and upload a screenshot here :)

**Comment by lhbvvvvv** [comment]
The feature with dark theme works well!

image

**Comment by tyn1998** [comment]
Figured a way out to change emoji picker color:

image

But the emoji picker will remain disabled until it is fine tuned for both themes. Let's leave the remaining TODOs to another PR 😆 

Hi @frank-zsy, do you think it's time to merge this PR and release a new version?

**Comment by frank-zsy** [comment]
Great, no need to fix all the minor things in this PR, let's merge this PR and release a new version!

/approve

**Pull request merged**
