### PR TITLE
chore: restructure the file tree and code of util functions

### LINKED ISSUE #668: [Chore] restructure the file tree and refactor code accordingly
### Description

- [ ] remove all unused code, such as files, functions, variables, etc.
- [ ] functions in `src/utils` -> `src/helpers`, and one function one file

image

After this task is finished, we can release v1.9.0, finally.

### PR DESCRIPTION
**Pull request by lhbvvvvv**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test
- [x] chore

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- resolve #668

## Details

Transfer the functions of `src/utils` to `src/helpers` and make each function correspond to a file. Remove some useless code of these functions. I didn't find useless code anywhere other than these files.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi @lhbvvvvv, would you mind changing the PR title with "chore: xxxxxx"? I will review your code in days :)

**Comment by tyn1998** [comment]
Hi @lhbvvvvv, I added some changes:

- [ ] format those unexpectedly unformatted code (I have no idea why they passed the husky test)
- [ ] use default export instead export in many helpers
- [ ] Bars/index.tsx -> Bars.tsx
- [ ] removed background.data.ts and related code

Would you mind having a test for the latest code? If everything works well, I'll merge this PR.

**Comment by lhbvvvvv** [comment]
I have tested the latest code. Everything works well!

**Review by tyn1998 — APPROVED** [review]
LGTM, thanks for your contribution! @lhbvvvvv

**Pull request merged**
