### PR TITLE
fix: the width of tooltip is too small

### LINKED ISSUE #473: [style] the width of tooltip is too small
### Description

After changing the legend name (which is longer then the original ones), the width of tooltip is too small, where we forgot to adjust.

image

### PR DESCRIPTION
**Pull request by wj23027**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

Related issues:

- fix #473

## Details

adjust the width of tooltip

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi, @wj23027, great job!

The changed code looks great to me. Could you also post a screenshot?

**Comment by wj23027** [comment]
Sure!
屏幕截图 2022-10-12 205509
屏幕截图 2022-10-12 205626
屏幕截图 2022-10-12 205742
In addition, @andyhuang18  and I cooperated to complete this task, which was a great improvement for us！

**Comment by xgdyp** [comment]
We found another interesting thing. In my screen(Mac M1) the tooltip is :
image
but in @zhicheng-ning , it's different

**Comment by zhicheng-ning** [comment]
Below is the effect in my monitor screen.
image

**Comment by tyn1998** [comment]
Thanks for all your feedback!

Hi @andyhuang18, thank you for your contribution, too! Would you like to experience a more strong sense of collaboration? By pushing another commit to solve the typo described by @xgdyp and @zhicheng-ning, your contribution can also be credited.

Follow these steps:

1. git remote add @wj23027's repo
2. git fetch her branch(i.e. this PR branch)
3. checkout a new branch from that branch
4. make your changes
5. git add commit and git push to your origin
6. make a PR to @wj23027's branch
7. @wj23027 merges your PR into her branch
8. Finally I will merge this PR into master

**Comment by andyhuang18** [comment]
OK！I will try to solve it.

**Review by tyn1998 — APPROVED** [review]
Hi, @andyhuang18, thanks for your contribution! I just removed the unrelated commits by `git rebase -i`:

image

You have done a great job, thank you!

/approve

**Pull request merged**
