### PR TITLE
feat: show more data (in an embeded way)

### LINKED ISSUE #395: [Feature] Add more data for hypercrx
### Description

I would like to add more data into Hypercrx. The first part is top 1 million repos(by star) on GitHub history details.

The data looks like below:

``` json
{
	"id": "7691631",
	"n": "moby/moby",
	"ic": {
		"20151": 5681,
		"20152": 5417,
		"20153": 6493,
		"20154": 7416,
		"20155": 6403,
		"20156": 5764,
		...
	},
	"oi": {
		"20151": 278,
		"20152": 255,
		"20153": 367,
		"20154": 403,
		"20155": 284,
		"20156": 342,
		...
	},
	"op": {
		"20151": 338,
		"20152": 339,
		"20153": 514,
		"20154": 537,
		"20155": 422,
		"20156": 341,
		...
	},
	"pm": {
		"20151": 245,
		"20152": 237,
		"20153": 406,
		"20154": 403,
		"20155": 330,
		"20156": 255,
		...
	},
	"rc": {
		"20151": 935,
		"20152": 1027,
		"20153": 1384,
		"20154": 2054,
		"20155": 1755,
		"20156": 913,
		...
	},
	"ad": {
		"20151": 21750,
		"20152": 19467,
		"20153": 42833,
		"20154": 47983,
		"20155": 69026,
		"20156": 76092,
		 ...
	},
	"de": {
		"20151": 6519,
		"20152": 71321,
		"20153": 20958,
		"20154": 27393,
		"20155": 20630,
		"20156": 64424,
		...
	},
	"s": {
		"20151": 763,
		"20152": 743,
		"20153": 870,
		"20154": 901,
		"20155": 824,
		"20156": 918,
		...
	},
	"f": {
		"20151": 899,
		"20152": 743,
		"20153": 1089,
		"20154": 963,
		"20155": 875,
		"20156": 985,
		...
	},
	"p": {
		"20151": 279,
		"20152": 217,
		"20153": 606,
		"20154": 426,
		"20155": 375,
		"20156": 442,
		...
	}
}
```

The field means:

- ic: issue comment count
- oi: open issue count
- op: open pull count
- mp: merge pull count
- rc: review comment count
- ad: merged additions code lines
- de: merged deletions code lines
- s: stars
- f: forks

All the data is grouped by month and only the number greater than 0 included.

All the data will be uploaded onto OSS storage and open to access.

Can you gays put these data into Hypercrx in proper way?

### LINKED ISSUE #432: [Feature] embeded view for star and fork (s,f)
### Description

A possible design:

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

Related issues:

- resolve #395
- resolve #432

## Details

This illustration shows what we want to achieve:

image

Subtasks:

- [x] star, fork
- [x] issue comment, open issue
- [x] op, mp, rc, ad, de
- [x] p
- [ ] i18n support (necessary?)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by tyn1998** [comment]
[react-tooltip](https://www.npmjs.com/package/react-tooltip) helps to implement the feature that when users hovering on certain elements there will be tooltips showing up and presenting anything we want.

image

**Comment by tyn1998** [comment]
embeded views for star and fork come out:

light theme:

image

image

dark theme:

image

image

**Comment by tyn1998** [comment]
Hi, @frank-zsy, I have some confusion about the data:

image

The json file:

image

I know the number of fork event is not equal to the number of fork, but how to explain the numbers show in the screenshot above? Why there is a huge gap?

**Comment by frank-zsy** [comment]
So cool!!

**Comment by frank-zsy** [comment]
@tyn1998 I think the data is not right, I will check it.

**Comment by frank-zsy** [comment]
I see, I put the data in wrong key, right now, the data in `f` is actually star count, in `s` is participants and in `p` is fork count. You can still use these keys and I will fix the data.

**Comment by frank-zsy** [comment]
And I think line chart can be used instead of bar chart which is more common in fork and star trending.

**Comment by frank-zsy** [comment]
If you are going to use hover to trigger the charts, please make sure that the mouse cursor can easily enter the chart and keep the charts showing so users can dive into the data. This may involve enlarge the detection fields of each charts.

I am not sure how to implement it but I think I expressed what I want.

**Comment by tyn1998** [comment]
> I see, I put the data in wrong key, right now, the data in `f` is actually star count, in `s` is participants and in `p` is fork count. You can still use these keys and I will fix the data.

Hah~got it.

> And I think line chart can be used instead of bar chart which is more common in fork and star trending.

emm, the value of each month represents increment, right? I considered line chart first but turned to bar chart since I thought "trending" requires total number rather icreament number. But I can add a line to existing bars so we can present them all in one chart. 



> If you are going to use hover to trigger the charts, please make sure that the mouse cursor can easily enter the chart and keep the charts showing so users can dive into the data. This may involve enlarge the detection fields of each charts.

Sure, I have considered this. The hovered box can be entered.

**Comment by frank-zsy** [comment]
The data update process should be completed by tomorrow morning and the data will be updated to 2022.8

**Comment by tyn1998** [comment]
> And I think line chart can be used instead of bar chart which is more common in fork and star trending.

Hi @frank-zsy, this is how a line chart looks like:

image

and its bar chart counterpart:

image

or a combination of both:

image

**Which way do you prefer? I'm ok with all of them :)** How about your guys? @will-ww @wxharry 

BTW, if we adopt line charts, I need to insert "zero" data for those months without a single event because of:

image

**Comment by frank-zsy** [comment]
I think combination version is better, but what I like is that use bar chart to show the increase value of each month and use line chart to show the accumulate value of all history.

**Comment by tyn1998** [comment]
Ok, I will implement it and update my progress here~

**Comment by frank-zsy** [comment]
But there is a problem that the accumulate value is not accurate since the data is from log events rather than API. So the users may feel quite confused and need to explain the difference. So we need to decide whether to add the accumulate line chart since it may cause extra cost of explanation.

**Comment by tyn1998** [comment]
For those months with 0 event, I insert zero data to make the line chart complete:

**Comment by tyn1998** [comment]
embeded view for issue details:

**Comment by tyn1998** [comment]
- [ ] tooltip format: not show day since the minimal is month

**Comment by tyn1998** [comment]
Finish basic version:

https://user-images.githubusercontent.com/32434520/193882359-fd4f84f4-570c-4a44-927b-a3cb79f16188.mp4

**Comment by wxharry** [comment]
The injections look perfect! Really appreciate your work these days! The interactions are smooth and I don't have any sense of being interrupted.
We still need a uniform title for these charts though. Whether to use plural form or not. And the nanme in the legends might be oversimplified. Maybe we could compose a detailed explanation and refer to that document some day.
image
image
Again. Really appreciate your work Lam!

**Comment by tyn1998** [comment]
@wxharry Thank your for yor appreciation!

> We still need a uniform title for these charts though. Whether to use plural form or not.

Agree. Actually I tried, but it was so hard for me to decide on the use of plural forms. Could you help? Another limitation is that Echarts doesn't provide an option to center the title text so if users want to center the title text they should adjust `left`, `top` and so on pixel by pixel, which is time consuming! Due to this, I tried to make the titles as long as the width of the charts to avoid trivial tuning, which might make the titles a little difficult to understand.



> And the nanme in the legends might be oversimplified.

Agree. But they cannot be long since the width of the chart is limited. Docs are good and some hover-to-show features also make sense (support in future).

**Comment by wxharry** [comment]
> Agree. Actually I tried, but it was so hard for me to decide on the use of plural forms. Could you help? 

IMO, using plural form for all titiles is fine.
> But they cannot be long since the width of the chart is limited.

Maybe use one word for each legend? Since we have a detailed title, it would be easy for users to understand what that is.

**Comment by wxharry** [comment]
Also, I noticed that there is a [code frequency section in insight tab](https://github.com/hypertrons/hypertrons-crx/graphs/code-frequency), which looks similiar to one of our graphs. Are these the same?
image

**Comment by tyn1998** [comment]
Not the same. Our data only count code line changes after PR merge, while the GitHub counterpart might also include code line changes made by direct push.

**Review by wxharry — APPROVED** [review]
LGTM

**Pull request merged**
