### PR TITLE
feat: add public configs for FastPR

### PR DESCRIPTION
**Pull request by frank-zsy**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [x] ci
- [ ] docs
- [x] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [x] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- #901 

## Details

This PR contains public config file, test and publish actions workflow:

- `public_configs/fast-pr-url-rules.js`: This file is the rules config file for FastPR, and other more static public configs file can be located in this directory in the future. I also add tests to each rule to check if the rule is valid.
- `scripts/test_configs.js`: This file is used to test the result of config files. Right now only FastPR configs need to be tested.
- `.github/workflow/publish_configs.yml`: This file is used to publish the public configs to OSS for HyperCRX to use, it will:
  - Run on master branch push.
  - Run configs test.
  - Upload public configs files to OSS.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by frank-zsy** [comment]
Also add an `expired` function for rules, this will be quite useful for commercial trails.

**Comment by frank-zsy** [comment]
Also add config for kaiwudb and the trail ends on 2015.1.1

**Comment by wangyantong2000** [comment]
Is this PR ready to merge now?

**Comment by frank-zsy** [comment]
> Is this PR ready to merge now?

Yes, I think this is ready

**Pull request merged**
