### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test
- [x] chore

## Details

Context: https://github.com/hypertrons/hypertrons-crx/pull/679#issuecomment-1564208683

@pranavshuklaa pointed out that she must change some versions of this project's dependencies to successfully start the project. So I guess that the current versions locked by `yarn.lock` might lead to errors in some machines with different setup from mine. Hence I did:

1. deleted `yarn.lock`
2. deleted `node_modules`
3. with node v20, ran `yarn install`
4. get a new `yarn.lock` and committed it to this branch then raised this PR

I would like to know if this new `yarn.lock` works in other machines. So would you guys mind helping to have a test? @lhbvvvvv @wxharry @pranavshuklaa

The procedure is:

1. `gh pr checkout 680`
2. delete your `node_modules`
3. `yarn install`
4. `yarn run start` and see if everything works fine

If all of you give a positive feedback, then this PR will be merged :)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by pranavshuklaa** [comment]
Thank you for making these changes!
I tested it on my local setup and everything seems fine ! you can proceed :)

**Comment by andyhuang18** [comment]
I tested it on my own machine. The result is no problem, can run smoothly.
Here is the test video:

https://github.com/hypertrons/hypertrons-crx/assets/50283262/1f9404a0-6edc-4d5e-b163-02cb1b1605ba

**Comment by wj23027** [comment]
I tested it and everthing works well~

**Comment by wxharry** [comment]
LGTM. Thanks!

**Review by lhbvvvvv — APPROVED** [review]
LGTM!

/approve

**Pull request merged**
