### PR TITLE
fix: fatal issue 382

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [x] refactoring

Related issues:

- #382 

## Details

It seems navigating between GitHub Tabs/pages will not trigger page reload anymore (like a SPA), which causes that our contentscript will only be run once when we open a tab that matches GitHub url and it damages our extension's core injection function since the contentscript of Hypercrx is designed to be run multiple times for each time the pages are redirected.

Currently, to address this fatal problem, the message passing API supported by chrome extension is applied to trigger `mainInject()` when the url of that tab is changed. The new strategy works but is encountered with unexpected css styles problem. 

All fluentUI elements behave bad after second, third or more `mainInject()` runs, like this:

image

image

I spent whole day but did not figure out a solution. This only happens on fluentUI elements. I have tried antd library today and find it works well under the new strategy.:

image

Maybe we should transfer to other UI library? I have no idea :(

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others

fluentUI elemtens' class names are dynamic like:

image

When second `mainInject()` is run, all fluentUI classes disappear.

### CODE REVIEW

**Comment by tyn1998** [comment]
Hello, @bytemain, would you mind please take a few minutes to read this PR description? I desperately need help 😆 .

**Comment by tyn1998** [comment]
Another bug has been introduced: hovering reactions cannot show detail overlay!

| before | after |
| --- | --- |
| image | image |

**Comment by bytemain** [comment]
> Hello, @bytemain, would you mind please take a few minutes to read this PR description? I desperately need help 😆 .
> 
> I find that OpenSumi also append something to class names:
> 
> image

these random strings are generated by webpack, because we enable the css modules feature in css-loader, it is a style isolation strategy.

more infomation you can see: https://webpack.js.org/loaders/css-loader/#modules

**Comment by tyn1998** [comment]
@bytemain, thank you very much! I'll look into that.

**Comment by tyn1998** [comment]
> Another bug has been introduced: hovering reactions cannot show detail overlay!

That happened after I introduced antd UI library to confirm that it was the fluent UI made the trouble. The result is, antd works as expected.

The downside is: I believe it conflicts with GitHub style sheets, which leads to reactions hovering overlay disappear.

**Comment by tyn1998** [comment]
> The downside is: I believe antd conflicts with GitHub style sheets, which leads to reactions hovering overlay disappear.

This is true. Antd is more a UI library, but a "design", so it does things that it believes right.

It always resets global style with [this style sheet](https://github.com/ant-design/ant-design/blob/master/components/style/core/global.less). 

[Here](https://zhuanlan.zhihu.com/p/50796186) is a workaround to avoid this forced style reset.

**Comment by tyn1998** [comment]
I infer that GitHub uses hotwired/turbo to speedup its SPA.
Fortunately there are some events to hook our code in GitHub
life cycle. See: https://turbo.hotwired.dev/reference/events

FluentUI is a css-in-js UI library, all styles are dynamicly
computed and [injected](https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/README.md#controlling-where-styles-are-injected) to several style tags, like:

```html
<head>
  <style data-merge-styles="true"></style>
  <style data-merge-styles="true"></style>
  <style data-merge-styles="true"></style>
</head>
```

Thease tags are only computed once for each component. But the
style tags are regarded as "provisional elements" by turbo and
most of them will be removed after each trubo:visit, leading to
style crash.

After reading the [source code](https://github.com/hotwired/turbo/blob/98cdc4037788f078a741c7fb50412db0101bcb97/src/core/drive/head_snapshot.ts#L58-L69) of turbo, I figure out a workaround.
By adding an id to all <style data-merge-styles="true"></style>
to make their outerHtml not be same, turbo will not regard them
as provisional elements and will keep them in headers.

**Pull request merged**
