### PR TITLE
[Refactor] Change OSS base URL into x-lab.info

### PR DESCRIPTION
**Pull request by frank-zsy**
Signed-off-by: frank-zsy <syzhao1988@126.com>

## Purpose
Change OSS file base URL into `http://hypertrons-oss.x-lab.info`.

## Proposed changes
More friendly URL under x-lab.info rather than aliyun.com

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

#### Types of changes
_What types of changes does your code introduce to hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments (Optional)
_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc..._
_Links to blog posts, patterns, libraries or addons used to solve this problem_

### CODE REVIEW

**Comment by heming6666** [comment]
LGTM.

You @frank-zsy can sign the CLA before I merge this PR ~

**Comment by frank-zsy** [comment]
> LGTM.
> 
> You @frank-zsy can sign the CLA before I merge this PR ~

Signed

**Comment by LiuChangFreeman** [comment]
This causes a problem that Chrome will not allow requests made over `http` rather than `https`.
Please deploy the back end service using `https`.

**Comment by frank-zsy** [comment]
> This causes a problem that Chrome will not allow requests made over `http` rather than `https`.
> Please deploy the back end service using `https`.

OK, HTTPS added. Now you can visit resources with `https` protocol.

**Pull request merged**
