### PR TITLE
docs: added "hypercrx" pronounciation to README

### LINKED ISSUE #446: [Docs] provide the pronounciation of "Hypercrx" in README
### Description

Someone asked me how to pronounce Hypercrx then I realized this important info had been missed for so long!

### PR DESCRIPTION
**Pull request by lmash12**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] docs

Related issues:

- resolve #446 

## Details

i have added hypercrx pronunciation in the readme file

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by wxharry** [comment]
Hey @lmash12 ! Thanks for your contribution! we might also want to add the pronunciation to [the Chinese version](https://github.com/hypertrons/hypertrons-crx/blob/master/README.zh-CN.md). Let me know if you need further information.

**Comment by lmash12** [comment]
> Hey @lmash12 ! Thanks for your contribution! we might also want to add the pronunciation to [the Chinese version](https://github.com/hypertrons/hypertrons-crx/blob/master/README.zh-CN.md). Let me know if you need further information.

Hi there, would I just be putting it in English as well? if not I am not sure I can handle translating correctly.

**Comment by tyn1998** [comment]
Hi @lmash12, thanks for your contribution! I will handle the Chinese part and push a commit to this PR.

**Review by tyn1998 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
