### PR TITLE
feat: add tooltip trigger

### LINKED ISSUE #692: [Improvement] How to trigger Tooltips in settings
### Description

Currently, the tooltips in the settings are triggered directly by hovering on the title container. IMO, it is no a big problem but it would be more intuitive if we could trigger the tooltips by adding a customize icon like this [demo](https://ant.design/~demos/components-form-demo-required-mark). Or, if the tooltips is unnecessary, we could consider removing it.

image

### PR DESCRIPTION
**Pull request by Vlad116**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [x] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- close #692

## Details

- Added a TooltipTrigger component with a question mark icon (accepts color and size as a string).
feat1
feat3_locale
- Added a tooltip visibility toggle at the top of the page
feat2
- Added a small margin at the bottom for the main content (it could overlap with the operating system navigation menu)
margin-bottom

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others

Demo:
https://github.com/hypertrons/hypertrons-crx/assets/32329117/788d1878-9dcb-4a8c-99fd-e4d76924c825

### CODE REVIEW

**Comment by Vlad116** [comment]
Hi, Harry) Sure, i can move the icon like on your screnshot and edit tooltip area how on it, also remove switch. 
I did not move TooltipTrigger to components, because often non-reusable components are made as subcomponents with index file.
Okay, I'll correct all comments. Could you clarify on the 5th point what exactly is wrong with the organization of the code if we abstract from the points indicated earlier?

**Comment by wxharry** [comment]
> Is the current icon right for you? @wxharry

I was expecting an information mark like in the previous screenshot if possible.


> Hi, Harry) Sure, i can move the icon like on your screnshot and edit tooltip area how on it, also remove switch. I did not move TooltipTrigger to components, because often non-reusable components are made as subcomponents with index file. 

I understand. I was expecting it to be resuable because we are planning some new features in this option page, so we might reuse the tooltips in the near future.


> Could you clarify on the 5th point what exactly is wrong with the organization of the code if we abstract from the points indicated earlier?

Sure. For example, you could refer to `src/pages/ContentScripts/features/developer-networks` to extract the icon. I understand it might not be the best way to do this, but we need to keep it identical within the project. Thanks for understanding.

**Comment by Vlad116** [comment]
Hello!)
I tried to make a dark background with transparency like in your screenshot, but it turned out to be not so easy with the implementation of the tooltip in this library. I removed the switch (and moved the TooltipTrigger to shared components), brought the tooltips to the following form:
PR

**Comment by Vlad116** [comment]
Are there any other changes needed to the current version or will we be able to close this PR soon? @wxharry

**Comment by wxharry** [comment]
> Are there any other changes needed to the current version or will we be able to close this PR soon? @wxharry

Slow down. Thanks for your passion but there is no need to rush. I am running some tests and thinking about some improvements.

**Comment by Vlad116** [comment]
> > Are there any other changes needed to the current version or will we be able to close this PR soon? @wxharry
> 
> Slow down. Thanks for your passion but there is no need to rush. I am running some tests and thinking about some improvements.

Of course, I'll just find out if any more updates are needed, I will check this thread once a day to find out

**Comment by wxharry** [comment]
It's fine if we cannot make it transparent. just make it to the default style as before will do.

**Comment by Vlad116** [comment]
> It's fine if we cannot make it transparent. just make it to the default style as before will do.

I'm update MR and add fix default style for TooltipTrigger

**Review by wxharry — CHANGES_REQUESTED** [review]
Everything looks good to me, except that it feels unnatural to me change the cursor to a question mark when hovering over the icon. Could you remove it?

I understand this style given by the demo I previously provided. Sorry for letting you change the style again and again!

**Comment by Vlad116** [comment]
@wxharry  Okay, no problem. I can change to default cursor style, sorry for awaiting

**Review by wxharry — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
