### PR TITLE
feat: add DashboardService & web-ext

### PR DESCRIPTION
**Pull request by heming6666**
- add `DashboardService` to render components.
- add `web-ext` to make it easier to run and debug the whole extention. 

### DashboardService

The main function is `renderDashboard` and it would:
- validate the configuration of components.
- render `React Component`.

The `ComponentConfig` is decleared as :
```
interface ComponentConfig {
  name: string,
  enable: boolean,
  insertElement?: ElementFunction,
  insertType?: InsertType,
  props?: any
}
```
It's quite simple right now. And maybe there are something that need to be added. 

### GitHubService

**Under development**.

Then `renderDashboard` would be called in `github/index.ts`: 
```js
import { loadConfigFromGithub } from '../common/ConfigService'
import { renderDashboard } from '../common/DashboardService';

const init = async (): Promise<void> => {
  const componentsConf = await loadConfigFromGithub();
  renderDashboard(componentsConf);
};
void init();
```
### ConfigService

**Under development**.

### web-ext

[web-ext](https://github.com/mozilla/web-ext) is a package that aims to help build, run, and test WebExtensions. It can open `Chrome` and load `Hypertrons-crx` into the browser automatically.

### CODE REVIEW

**Comment by heming6666** [comment]
Currently `switch-case` is used to load the components:
```js
switch (name) {
      case 'DeveloperCollabrationNetwork':
        render(
          <DeveloperCollabrationNetwork props={props} />,
          insertItem,
        );
        break;
      default:
        break;
    }
```

Actually I tried to use `React.lazy()` and `dynamic import`  to load the components dynamically. 
```js
const Component = React.lazy(() => import(`../components/${name}`));
```
But I just got `Loading chunk 1 failed` exceptions. Here's the similar situation: https://stackoverflow.com/questions/53704950/webpack-code-splitting-loading-chunk-failed-error-wrong-file-path. 

And I tried the answer but it still didn't work. Here's the corresponding branch: https://github.com/heming6666/hypertrons-crx/tree/dynamic-import.

Here's the code: 
- https://github.com/heming6666/hypertrons-crx/blob/3b68491a45a3bdc6df9e3e0a35ef2b61faba0afb/webpack.config.js#L46
- https://github.com/heming6666/hypertrons-crx/blob/3b68491a45a3bdc6df9e3e0a35ef2b61faba0afb/src/pages/Content/common/DashboardService.tsx#L55

image

I will keep trying... Do you @LiuChangFreeman have any suggestions ?

**Review by LiuChangFreeman — COMMENTED** [review]
All OK

**Comment by LiuChangFreeman** [comment]
Maybe It is caused by security checks of the browser.

**Comment by LiuChangFreeman** [comment]
> Maybe It is caused by security checks of the browser.

I'll find out how to get it work after this commit is merged.

**Pull request merged**
