### PR TITLE
fix the doc, when select the unzipped folder return err.

### PR DESCRIPTION
**Pull request by stevending1st**
## Purpose
When I install the APP, I can not install the APP, I found the docs was wrong.

## Proposed changes
- [ ] /INSTALLATION.md
- [ ] /INSTALLATION.zh-CN.md

#### Open Questions and Pre-Merge TODOs
- [x] Use github checklists. When solved, check the box and explain the answer.

#### Types of changes
_What types of changes does your code introduce to hypertrons-crx?_
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Approach
_How does this change address the problem?_

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments (Optional)
I can not open the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx), so I can not sign the CLA.

### CODE REVIEW

**Comment by LiuChangFreeman** [comment]
Please sign the CLA otherwise we can't merge your pull request

**Comment by stevending1st** [comment]
> Please sign the CLA otherwise we can't merge your pull request

I have some doubts, please see: #182 .

**Comment by heming6666** [comment]
@stevending1st We have updated the right version of CLA. You can sign the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx) now and this PR will be merged once you sign it.

**Comment by stevending1st** [comment]
> @stevending1st We have updated the right version of CLA. You can sign the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx) now and this PR will be merged once you sign it.

thx for your workong!  I signed th CLA just now. Happy Coding!

**Review by heming6666 — APPROVED** [review]
/approve

**Pull request merged**
