### PR TITLE
Feature/328 added profile picture in dev network and update readme

### PR DESCRIPTION
**Pull request by smitsekhadiaa**
## Purpose
Solution to Issue #328 

Replace the nodes with Github profile pictures of the contributors in Active Developer Collaboration network and Developer Collaboration network and update Readme.

## Proposed changes

image

image

#### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by tyn1998** [comment]
Hey @smitsekhadiaa, I think your gif size is too big, which is not friendly to visitors who have a bad internet connection. Could you please compress it to a small gif?

image

**Comment by smitsekhadiaa** [comment]
> Hey @smitsekhadiaa, I think your gif size is too big, which is not friendly to visitors who have a bad internet connection. Could you please compress it to a small gif?
> 

yes i'll do it right now👍

**Comment by tyn1998** [comment]
And you can also zoom in the graph then record it to make it more clear in README~

**Comment by smitsekhadiaa** [comment]
yes sorry @tyn1998 
i read your comment just now after making commits (of reducing the size of the gifs),
ill record it again and update it👍

**Comment by tyn1998** [comment]
Sorry, but I think the size is still too big for me.

image

**Comment by smitsekhadiaa** [comment]
oh okay @tyn1998 
sorry,
I'll reduce it to KB's and then upload it

**Comment by tyn1998** [comment]
Try different Gif recorders. I'm using Gifox, which only supports MacOS.

**Comment by tyn1998** [comment]
Thank you @smitsekhadiaa, it looks great to me! Is this PR ready to be merged(squash merge)?

**Comment by smitsekhadiaa** [comment]
yes @tyn1998 
I think it is ready to be merged👍

**Pull request merged**
