### PR TITLE
refactor: remove unnecessary injected script

### LINKED ISSUE #428: [refactor] injectedScript is unnecessary so remove it
### Description

I wrongly thought we need an injectedScript to add event listener to the events "turbo:before-visit" and "turbo:load":

https://github.com/hypertrons/hypertrons-crx/blob/4dd7f092594924c0ee97e4cc87ae55f546feba31/src/pages/ContentScripts/index.ts#L1-L12

That was a mistake. Simply adding event listener in content script works fine, so remove the injectedScript.

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] refactor

Related issues:

- resolve #428 

## Details

Removed related code and moved document.addEventListener(xxx, xxx) to contentscript.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others

N.A.

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi, @wxharry, please `gh pr checkout 429` and test if everything works fine. :coffee:

**Review by wxharry — APPROVED** [review]

**Comment by wxharry** [comment]
LGTM

**Comment by tyn1998** [comment]
Hi @frank-zsy, can you help us find out why @wxharry 's `/approve` didn't work? Menbotics even did not tag the label.

https://github.com/hypertrons/hypertrons-crx/blob/4dd7f092594924c0ee97e4cc87ae55f546feba31/.github/hypertrons.json#L97-L106

**Comment by frank-zsy** [comment]
@tyn1998 Config takes effect now, there maybe something with some repo suspends Menbotics which leads to an exception on server side. I have fixed this bug for now.

**Pull request merged**
