### PR TITLE
feat: replace HyperCRX networks component with OSGraph networks

### PR DESCRIPTION
**Pull request by wangyantong2000**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [x] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

#834 

## Details

https://github.com/user-attachments/assets/05639c3c-b8e5-464d-96fd-fb4ba4876396
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by wangyantong2000** [comment]
The last time OSGraph personnel raised the following questions:
1. Caves height issue
2. Refreshing the page graph will result in a scaling process
3. Click on the percetor, refresh, and the tab activates insights
4. The OSGraph link in the upper right corner of the graph only leads to the homepage and cannot directly reach the corresponding canvas of the project.
Currently, problem 3 has been resolved, and the following will address the above issues.

**Comment by wangyantong2000** [comment]
https://github.com/user-attachments/assets/9c77b2c3-ffa8-4950-9f65-f64e5d4f3ccd


https://github.com/user-attachments/assets/28601c07-6004-4cff-97c9-9c149364eac5

Several issues have been resolved at present. As shown above. And for questions 1 and 2, regarding height and refresh scaling, I believe it is due to issues with the OSGraph webpage itself. As shown in the video below.

https://github.com/user-attachments/assets/8680db51-2556-4eb3-918f-e445bf52f815

**Comment by HalloMelon** [comment]
In order to compress the video, the image quality is reduced, but the operation process is very smooth.
However, there is a slight delay when the personal page bar is first opened.

https://github.com/user-attachments/assets/abf4c9ab-7754-4b45-98c8-7a32c6270757

https://github.com/user-attachments/assets/68bf602b-5886-4a6c-a645-91be3a09abd5

**Comment by HalloMelon** [comment]
Tested the updated code with no problems!
https://github.com/user-attachments/assets/d3916e63-b339-40ba-bd9f-6dc3d265af77

**Comment by wxharry** [comment]
It takes time to show graphs in repos like [vscode](https://github.com/microsoft/vscode/pulse?redirect=perceptor). Just want to add it here as a reminder, so we are aware of that.

**Comment by HalloMelon** [comment]
The problem of blank space has been solved. The network diagram is displayed very quickly in vscode. And the Contributor Activity Racing Bar may be processing slowly because it has to display 3940 pieces of data.

https://github.com/user-attachments/assets/f7f5e013-075b-4dc9-82a3-7693b65a8ecc

**Comment by frank-zsy** [comment]
Is there any other problems about this PR? Can we have a release of new version HyperCRX this week before the launch of OSGraph 2.0 in Shanghai 2024.9.6?

**Comment by wangyantong2000** [comment]
> The problem of blank space has been solved. The network diagram is displayed very quickly in vscode. And the Contributor Activity Racing Bar may be processing slowly because it has to display 3940 pieces of data.
> 
>  Clipchamp.mp4

After raising this question, I did not make any adjustments to address this question. I just modified the style elsewhere. Testing should be conducted comprehensively based on PR status, problem description, and submission.

**Comment by wangyantong2000** [comment]
> It takes time to show graphs in repos like [vscode](https://github.com/microsoft/vscode/pulse?redirect=perceptor). Just want to add it here as a reminder, so we are aware of that.
Specifically, which type of chart does it refer to, the OSgraph chart or the Racing Bar chart.

**Comment by wangyantong2000** [comment]
>  It takes time to show graphs in repos like [vscode](https://github.com/microsoft/vscode/pulse?redirect=perceptor). Just want to add it here as a reminder, so we are aware of that.

 Specifically, which type of chart does it refer to, the OSgraph chart or the Racing Bar chart.The first loading of two components may take some loading time

**Comment by wangyantong2000** [comment]
> Is there any other problem with this PR? Can we have a release of new version HyperCRX this week before the launch of OSGraph 2.0 in Shanghai 2024.9.6?

The issues mentioned in the DingTalk group last time have been resolved. If no other issues are raised in the future, it can be merged and released.

**Comment by wangyantong2000** [comment]
https://github.com/user-attachments/assets/fa9853da-015d-4a20-af5a-c9aa55250081

Regarding clicking on the chart to redirect to the URL of osgrpah. In the video, it is better to jump in place or to jump to a new tab. I feel that jumping to a new tab seems better.

**Comment by wxharry** [comment]
> > It takes time to show graphs in repos like [vscode](https://github.com/microsoft/vscode/pulse?redirect=perceptor). Just want to add it here as a reminder, so we are aware of that.
> 
> Specifically, which type of chart does it refer to, the OSgraph chart or the Racing Bar chart.The first loading of two components may take some loading time.

The OSGraphs were slow, but they are better now. we can do nothing about this since it is not our work.

**Comment by wxharry** [comment]
> Regarding clicking on the chart to redirect to the URL of osgrpah. In the video, it is better to jump in place or to jump to a new tab. I feel that jumping to a new tab seems better.

vote for a new tab. The button is confusing IMO, we might need some tooltips or button text to show what does this button do. It could be bad if a user click on the button and jump to graph but if it is a new tab, they will get to know what happened.

**Comment by wangyantong2000** [comment]
> 
> The OSGraphs were slow, but they are better now. we can do nothing about this since it is not our code.

And for the three iframes in the interceptor interface, I delay each iframe by 500ms sequentially. Otherwise, in the early stages of development attempts, some of the three requests made simultaneously may return a blank interface

**Pull request merged**
