### PR TITLE
style: add dark mode for hypertron command pop up window

### PR DESCRIPTION
**Pull request by andyhuang18**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test
- [x] style

 Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- style #512 

## Details

light mode screenshot
light mode

dark mode screenshot
dark mode

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others
Thanks @wj23027  and @lucky_xmyu :)

### CODE REVIEW

**Comment by tyn1998** [comment]
image

Hi, @andyhuang18, thanks for your contribution.

There is also a triangle that should be colored :)

**Comment by andyhuang18** [comment]
Copy that!

> image
> 
> Hi, @andyhuang18, thanks for your contribution.
> 
> There is also a triangle that should be colored :)

Copy that!

**Comment by andyhuang18** [comment]
dark mode screenshot
dark mode ss

light mode screenshot
light mode ss

**Comment by andyhuang18** [comment]
I found the usage of ‘callout’ in hypertrons-crx\node_modules\@fluentui\react\lib\components\Callout\Callout.types.d.ts
It's helps a lot.

callout

**Review by tyn1998 — APPROVED** [review]
LGTM now, thank you @andyhuang18!

image

/approve

**Pull request merged**
