### PR TITLE
refactor: DeveloperNetwork -> developer-networks

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [x] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- related #574

## Details

| Light | Dark |
| --- | --- |
| image | image |
| image | image | 

- [x] No fluentUI anymore
- [x] new third-party component [ReactModal](https://github.com/reactjs/react-modal)
- [x] DeveloperNetwork -> developer-networks
- [x] new icons (old icons are from fluentUI so we must have new ones)
- [x] remove useless files and code (such as `anchors/`, `views/`)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others

N.A.

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi @wj23027 @andyhuang18 @lhbvvvvv, could you pull this PR and have a test?

Check points:

- both themes
- navigating from tabs/pages
- go forward/backward between history
- ...

**Comment by lhbvvvvv** [comment]
GIF 2023-4-2 18-40-25


If the page I go back to is not the user's home page, the graph doesn't disappear until I go back to the user's home page again.

**Comment by tyn1998** [comment]
Hi, @lhbvvvvv, thanks for your feedback. I have fixed the bug, may you fetch the latest branch and check it again? Then you could merge this PR if all things look good to you.

**Review by lhbvvvvv — APPROVED** [review]
LGTM!

**Pull request merged**
