### PR TITLE
refactor: upgrade react version

### PR DESCRIPTION
**Pull request by wangyantong2000**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [x] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- keyword #873

## Details

Upgrade the React version to 18+
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by wangyantong2000** [comment]
@Xsy41. Need your help to check if it is still running normally and if there are any omissions.

**Comment by Xsy41** [comment]
> @Xsy41. Need your help to check if it is still running normally and if there are any omissions.

It's checked out. There's no problem.

**Comment by wangyantong2000** [comment]
@YaoYao-Pig also wants to participate in this project and can conduct a test on this PR first.

**Comment by wangyantong2000** [comment]
Unfortunately, the content in the NativePopover.tsx file has not been improved. People with relevant knowledge can provide assistance. I will move on to other content first.

**Comment by wangyantong2000** [comment]
> Unfortunately, the content in the NativePopover.tsx file has not been improved. People with relevant knowledge can provide assistance. I will move on to other content first.

Thank you to @Xsy41 and @YaoYao-Pig for pointing out mistakes and helping to correct them. Everyone can try again now, there shouldn't be any problems.

**Comment by Xsy41** [comment]
> > Unfortunately, the content in the NativePopover.tsx file has not been improved. People with relevant knowledge can provide assistance. I will move on to other content first.
> 
> Thank you to @Xsy41 and @YaoYao-Pig for pointing out mistakes and helping to correct them. Everyone can try again now, there shouldn't be any problems.

Yes, it is no longer a problem.

**Comment by YaoYao-Pig** [comment]
> > Unfortunately, the content in the NativePopover.tsx file has not been improved. People with relevant knowledge can provide assistance. I will move on to other content first.
> 
> Thank you to @Xsy41 and @YaoYao-Pig for pointing out mistakes and helping to correct them. Everyone can try again now, there shouldn't be any problems.

OK！I think there are no problem now

**Pull request merged**
