### PR TITLE
feat: media player controllers for contributor activity racing bar

### LINKED ISSUE #234: [Feature] Show the top devleoper and scores.
这个活跃度指标确实很客观，我们打算作为衡量社区贡献的指标。

比如我们有技术委员会，那么谁是核心开发者，谁贡献大，谁可以发文化衫，凭感觉很容易得罪人，用这个指标作为重要参考，就会很好。

但是目前看不到项目的top开发者的分数，有个关系图还需要一个个去看，而且还不知道哪些是项目的开发者，哪些不是，非常麻烦。

image

比如左侧的图，要拿到top10就很困难，要人眼判断下哪个球大，有些还不是开发者是机器人账号(codecov-commenter)。

是否可以在右侧列出top user和分数呢？

### LINKED ISSUE #729: [Feature] Media player control for racing bar
### Description

Currently, our racing bar chart only has a replay button, we want to add more media player control on repo activity racing bar: 

- The basic control should include Pause, Play/resume, Previous, Next besides Replay.
- Click on Pause/Play control should be able to Pause/resume the racing bar.
- Click on Previous/Next controls should be able to jump to the previous/next month of current month.
- Can go to a specific position.

### PR DESCRIPTION
**Pull request by tyn1998**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [x] feat
- [ ] fix
- [ ] perf
- [ ] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- resolve #729
- resolve #234

## Details

In this PR I added media player controllers for the Racing Bar. I could say now the Racing Bar is the most complex feature in Hypercrx 😆 .

Video:

https://github.com/hypertrons/hypertrons-crx/assets/32434520/ec76ed01-11fc-4967-a124-5f2018328494

In `light` theme:

image

In `dark` theme:

image

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

### CODE REVIEW

**Comment by tyn1998** [comment]
May I request for your review? @lhbvvvvv @wxharry 

@zhaosj975 @Tenth-crew @wangyantong2000 Guys need you doing some tests, again ✌️ 

@andyhuang18 @wj23027 You two might benifit from this PR and gain knowledges for your OSPP projects.

**Comment by wxharry** [comment]
Markdown file formats are changed in this pr, did you run prettier for all files including the markdowns? @tyn1998

**Comment by wxharry** [comment]
It still takes time to go to the latest bar chart when playing, espcially for large repo like [vscode](https://github.com/microsoft/vscode/pulse?redirect=perceptor). Can we have a button to jump to the latest chart better support [this issue](https://github.com/hypertrons/hypertrons-crx/issues/234)?

**Comment by tyn1998** [comment]
> Markdown file formats are changed in this pr, did you run prettier for all files including the markdowns? @tyn1998

I checkedout this branch from https://github.com/hypertrons/hypertrons-crx/pull/744. In that PR markdown files are changed unintentionally by @lhbvvvvv but it's ok to keep those changes.

> It still takes time to go to the latest bar chart when playing, espcially for large repo like [vscode](https://github.com/microsoft/vscode/pulse?redirect=perceptor). Can we have a button to jump to the latest chart better support [this issue](https://github.com/hypertrons/hypertrons-crx/issues/234)?

When the racing bar is first rendered, it shows the latest data. The `next` button also support long press to go to the latest month. You may have a try :D

**Comment by wangyantong2000** [comment]
https://github.com/hypertrons/hypertrons-crx/assets/135088663/a4cc170e-9c0b-4a5f-8ee0-daadbac07ae4

**Comment by Tenth-crew** [comment]
After clicking Pause, the animation will stop after a delay rather than immediately
https://github.com/hypertrons/hypertrons-crx/assets/68376741/7b38c565-9241-47ce-9d18-6714fa716391

**Comment by wangyantong2000** [comment]
https://github.com/hypertrons/hypertrons-crx/assets/135088663/8e4373b4-74ad-46a3-890f-61445a7356cf

**Comment by tyn1998** [comment]
@Tenth-crew @wangyantong2000 Thank you for testing!

> After clicking Pause, the animation will stop after a delay rather than immediately

This is expected, since the running racing bar is not actually a video :)

**Comment by zhaosj975** [comment]
it is more nice~
https://github.com/hypertrons/hypertrons-crx/assets/79428895/82997c0c-82ba-4863-873f-bb7398a93908

**Review by lhbvvvvv — APPROVED** [review]
LGTM!

/approve

**Pull request merged**
