### PR TITLE
refactor: replace all occurrences of "Influence" with "OpenRank"

### LINKED ISSUE #526: [Refactor] replace all occurrences of "Influence" with "OpenRank"
### Description

As discussed in https://github.com/hypertrons/hypertrons-crx/issues/515#issuecomment-1314794762, "Influence" will be no longer used. We need to replace the occurrences of the name with "OpenRank" in all places such as code objects and docs.

### PR DESCRIPTION
**Pull request by Zzzzzhuzhiwei**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [x] docs
- [ ] feat
- [ ] fix
- [ ] perf
- [x] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- close #526 

## Details

- [x] I have replaced all occurrences of "Influence" with "OpenRank" in codebase
- [x] replace all occurrences of "Influence" with "OpenRank" in picture

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others

N.A.

### CODE REVIEW

**Comment by Zzzzzhuzhiwei** [comment]
I will replace all occurrences of "Influence" with "OpenRank" in the pictures  which contain "Influence" next.

**Comment by Zzzzzhuzhiwei** [comment]
image
image
image

**Comment by tyn1998** [comment]
Oops, an occurrence was omitted :)

image

**Comment by Zzzzzhuzhiwei** [comment]
I will replace it now. 😄

**Review by tyn1998 — APPROVED** [review]
LGTM, thank you very much!

/approve

**Pull request merged**
