### PR TITLE
refactor: add perceptor tab and layout & relevant feature injection

### PR DESCRIPTION
**Pull request by wxharry**
## Brief Information

This pull request is in the type of ([more info](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) about types):

- [ ] build
- [ ] ci
- [ ] docs
- [ ] feat
- [x] fix
- [ ] perf
- [x] refactor
- [ ] test

Related issues ([all available keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)):

- #574 

## Details
1. refactor perceptor tab and perceptor layout based on new injection mechanism
2. add advance & additional listener to the injection mechanism
3. fix a bug in `asLongas` in the mechanism

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/hypertrons/hypertrons-crx/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/hypertrons/hypertrons-crx)

## Others
To better fit the perceptor tab, especially for the selected situation. I add some new features to the injection mechanism.

I tried my best to make the unselected and selected on tabs to be as natural as possible. But there is still a probable blink between insights tab and perceptor tab when we load `/pulse?redirect=perceptor` directly (rather than click on tab). I assume that Github has some selecting functions fired at `turbo:load` which is causing this.

Sorry for the mess, I should've separated my changes but when I figured that out, all is strongly connected. Please feel free to comment below or DM me for any detail.

### CODE REVIEW

**Comment by tyn1998** [comment]
Hi @wxharry, I'm testing this PR and find tab highlight doesn't work:

https://user-images.githubusercontent.com/32434520/222629157-fc5a3241-be28-481a-9ffb-63af96b5f4e9.mp4

Does it work on your machine?

> add advance & additional listener to the injection mechanism

I'm learning how rgh implements its Bug Tab feature and then gonna learn this mechanism :)

> But there is still a probable blink between insights tab and perceptor tab when we load `/pulse?redirect=perceptor` directly (rather than click on tab).

rgh's Bug Tab also blinks (for a really short time).

And another thing: I've pushed to v1.9.0 yesterday to merge changes from master. For this branch, it is ok to not have a rebase on the latest v1.9.0. You decide :)

**Comment by wxharry** [comment]
I've fixed the bug. I cannot tell what is causing this. For this newest edition in this pr, the blink is longer than the previous. No blink when navigating between tabs.

**Comment by tyn1998** [comment]
Hi, @wxharry, the highlight shows up! But there is still a bug when I navigate between browser history:

https://user-images.githubusercontent.com/32434520/222873291-e113f68e-e896-4598-93b6-5bfd7dac655c.mov

**Comment by wxharry** [comment]
> Hi, @wxharry, the highlight shows up! But there is still a bug when I navigate between browser history:

Thanks for issuing that out. Looks like it is caused by the underlying logic of github website. Could you try if you could reproduce this bug with hypercrx disabled?

**Comment by tyn1998** [comment]
Tested it with Hypercrx being disabled. You just found a GitHub bug! LOL

**Review by tyn1998 — APPROVED** [review]
Great job, @wxharry! I had a review and added several small commits for non-functional improvements :)

Hello, @lhbvvvvv, could you `gh pr checkout 589` and have a test? If everything works well, you can press the "Squash and merge" button to merge this PR!

**Comment by lhbvvvvv** [comment]
> Great job, @wxharry! I had a review and added several small commits for non-functional improvements :)
> 
> Hello, @lhbvvvvv, could you `gh pr checkout 589` and have a test? If everything works well, you can press the "Squash and merge" button to merge this PR!

Yes, I can have a test!

**Comment by lhbvvvvv** [comment]
GIF 2023-3-8 15-24-45

It looks good.

**Pull request merged**
